### ISSUE TITLE
NAACL 2016 proceedings URL is 404

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [WING-NUS/acl#29]
On http://aclanthology.info/events/naacl-2016, the NAACL 2016 proceedings URL (http://aclweb.org/anthology/N16-1) is 404.

![image](https://cloud.githubusercontent.com/assets/15331/19839258/d4de97b0-9eb4-11e6-9c78-405805ad6082.png)

**Comment by knmnyn** [comment]
Hi Frank:

Thanks for reporting this problem.  We are corresponding with the
publications chair of NAACL 2016 to correct this oversight.

We will close this thread (and hence you will get a notification) once the
file is publicly available.   -M

**Comment by knmnyn** [comment]
Hi Frank,

The full volumes are now accessible in the ACL Anthology.  Thanks for
your patiences.

Closes #29.

-M
